## Row Selection 

In [10]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# array[start:end:step]

#accessing row
print(array[2])
print(array[-1])

print(array[0:3])
print(array[:])

print(array[::2])
print(array[1::2])
print(array[::-2])

[ 9 10 11 12]
[13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [13 14 15 16]]
[[13 14 15 16]
 [ 5  6  7  8]]


## Column Selection


In [21]:

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])


print(array[:, 0])
print(array[:, -1])


print(array[:, 0:3])
print(array[:, 1:])
print(array[:, 1::2])
print(array[:, ::-2])


print(array[0:2, 0:3])
print(array[2:, 0:2])
print(array[2:, 2:])




[ 1  5  9 13]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]
[[1 2 3]
 [5 6 7]]
[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]
