## Scaler Arithmatic

In [6]:
import numpy as np

# Scaler Arithmatic : Single Value
array = np.array([1,2,3])
print(array)

print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array**5)




[1 2 3]
[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


## Vectorized Math Function 


In [11]:
import numpy as np

# Vector : Linear Algebra term/ One D Array 
array = np.array([1.01, 2.5, 3.99])

print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))

#Built in constant
print(np.pi)






[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [13]:
radii = np.array([1,2,3])

print(np.pi*radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


# Element Wise Arithmatic

In [ ]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)






[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


# Comparison Operator

In [24]:
scores =np.array([91, 55, 100, 73, 82, 64])
print(scores== 100)
print(scores>60)
print(scores<60)

scores[scores<60]=00
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]
