# Filtering 
Refers to selecting elements from an that match a given condition 


In [2]:
import numpy as np

In [ ]:
# Boolean Indexing

ages = np.array([
    [21, 17, 19, 20, 16, 30, 18, 65],
    [39, 22, 15, 99, 18, 19, 20, 21]
])

teenagers = ages[ages<18]
print(teenagers)

adults = ages[(ages>=18) & (ages<65)]
print(adults)

seniors = ages[ages>=65]
print(seniors)

even = ages[ages%2==0]
print(even)

odd = ages[ages%2!=0]
print(odd)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [11]:
# Where function 

ages = np.array([
    [21, 17, 19, 20, 16, 30, 18, 65],
    [39, 22, 15, 99, 18, 19, 20, 21]
])

adults = np.where(ages>=18, ages, 0)
print(adults)


[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
