# Random Number

In [1]:
import numpy as np

In [13]:
rng = np.random.default_rng(seed=1) #seed will return same result
print(rng.integers(low=1, high=101, size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [21]:
np.random.seed(1)
print(np.random.uniform(low=-1, high=1, size=(3, 2))) #Uniform Distribution 

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [26]:
rng = np.random.default_rng()

array= np.array([1,2,3,4,5])

rng.shuffle(array)

print(array) 

[1 3 4 2 5]


In [29]:
rng = np.random.default_rng()

fruits = np.array(["🍎", "🍊", "🍌", "🥥","🍍"]) 
fruit = rng.choice(fruits, size=(3,3))
print(fruit)

[['🥥' '🍎' '🍎']
 ['🍌' '🥥' '🥥']
 ['🍌' '🥥' '🍊']]
