## Numpy Array and Basics 

In [3]:
import numpy as np

In [4]:
arr_1d=np.array([1,2,3,4,5])
print("Id Array : ",arr_1d)

arr_2d=np.array([[1,2,3,], [4,5,6]])
print("2d Array : ",arr_2d)

Id Array :  [1 2 3 4 5]
2d Array :  [[1 2 3]
 [4 5 6]]


## List vs Numpy Array


In [5]:
py_list = [1,2,3]
print("Python List Multiplication : ", py_list*2)

np_array=np.array([1,2,3])
print("Python Array Multiplication : ", np_array*2)

Python List Multiplication :  [1, 2, 3, 1, 2, 3]
Python Array Multiplication :  [2 4 6]


In [ ]:
import time

start = time.time()
py_list= [i*2 for i in range(1000000)]
print("\n List Op Time : ", time.time()-start)


start = time.time()
np_array=np.arange(1000000)*2  # start, stop, step
print("\n Np Array Op Time : ", time.time()-start)



 List Op Time :  0.1461043357849121

 Np Array Op Time :  0.006512641906738281


## Creating array from Scratch 

In [15]:
zeros= np.zeros((3,4))
print("Zeros Array : \n", zeros)

ones = np.ones((4, 5))
print("Ones Array : \n", ones)

full = np.full((3,3), 7)
print("Full Array : \n", full) 



random= np.random.random((2,3))
print("Random Array : \n", random)\
    
    
sequence= np.arange(0, 10, 2)
print("Sequence Array : \n", sequence)

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array : 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random Array : 
 [[0.44731517 0.11413589 0.55447378]
 [0.25052044 0.64941724 0.73072818]]
Sequence Array : 
 [0 2 4 6 8]


## Vector, Matrices and Tensor

In [4]:
vector=np.array([1,2,3])
print("Vector array : ", vector)


matrix= np.array([[1,2,3], 
          [4,5,6]])
print("Matrix : ", matrix)

tensor= np.array([
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]        
    ]
])
print("Tensor : ", tensor)

Vector array :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


## Array Properties

In [5]:
arr= np.array([[1,2,3],[4,5,6]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("DType : ", arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
DType :  int32


## Array Reshaping

In [8]:
arr = np.arange(12)
print("OG array :", arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array : \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array : ", flattened)


#Returns view instead of copy 
raveled = reshaped.ravel()
print("Raveled Array : ", raveled)

#Tranpose
transposed=reshaped.T
print("Transposed Array: \n", transposed)



OG array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
