## Numpy Array Operation

In [1]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing : ", arr[2:7])
print("With Step : ", arr[1:8:2])
print("Negative Indexing : ", arr[-3])

Basic Slicing :  [3 4 5 6 7]
With Step :  [2 4 6 8]
Negative Indexing :  8


In [7]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])
print("Specific Element : ", arr_2d[1,2])
print("Entire Row : ", arr_2d[1])
print("Entire Column : ", arr_2d[:, 1])

Specific Element :  6
Entire Row :  [4 5 6]
Entire Column :  [2 5 8]


## Sorting 

In [14]:
unsorted=np.array([2,5,6,4,8,9,7,23,3])
print("Sorted Array : ", np.sort(unsorted))

arr_2d=np.array(
    [
        [3,1],
        [1,2],
        [2,3]
    ]
)

print("Sorted 2d Array by column : \n", np.sort(arr_2d, axis=0))
print("Sorted 2d Array by rows : \n", np.sort(arr_2d, axis=1))

Sorted Array :  [ 2  3  4  5  6  7  8  9 23]
Sorted 2d Array by column : 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d Array by rows : 
 [[1 3]
 [1 2]
 [2 3]]


## FIlter


In [15]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = number[number%2==0]
print("Even Number : ", even_num)

Even Number :  [ 2  4  6  8 10]


## Filter With Mask


In [17]:
mask=number>5
print("Numbers greater than 5 : ", number[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [19]:
indices = [0, 2, 4]
print(number[indices])

where_result=np.where(number>5)
print("NP Where : ", number[where_result])

[1 3 5]
NP Where :  [ 6  7  8  9 10]


In [22]:
#np.where() : Create Array with specific condition 
condition_array=np.where(number>5, number*4, number)
print(condition_array)

condition_array1=np.where(number>5, "true", "false")
print(condition_array1)

[ 1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and Removing Data

In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

# combined=arr1+arr2
combined = np.concatenate((arr1, arr2))
print("Combined Array : ", combined)

Combined Array :  [1 2 3 4 5 6]


### Array Compatibility

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6, 7])
c = np.array([7,8,9])

print("Compatibility shapes : ", a.shape == b.shape)

Compatibility shapes :  False


In [30]:
og = np.array([
    [1,2],
    [3,4]
])
new_row= np.array([[5,6]])

w_new_row=np.vstack((og, new_row))
print(og)
print(w_new_row)

new_col = np.array([
    [7], [8]
    ])    
w_new_col=np.hstack((og, new_col))
print(og)
print(w_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [31]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 3)
print("Array after deletion : ", deleted) 

Array after deletion :  [1 2 3 5]
